CREATE TABLE IF NOT EXISTS accounts(
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    login VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    surname VARCHAR(255),
    patronym VARCHAR(255),
    email VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS states(
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS people(
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255),
    surname VARCHAR(255),
    patronym VARCHAR(255),
    birthday DATE,
    gender TINYINT,
    telephone VARCHAR(255),
    email VARCHAR(255),
    address VARCHAR(255),
    education TINYINT,
    comment VARCHAR(255),
    about TEXT,
    received_when DATE,
    created_by INT UNSIGNED,
    created_when DATE,
    state_id INT UNSIGNED,
    checked BOOLEAN NOT NULL DEFAULT FALSE,
    ignored BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY(created_by) REFERENCES accounts(id) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY(state_id) REFERENCES states(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS vacancies(
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255),
    is_open BOOLEAN NOT NULL DEFAULT TRUE,
    created_by INT UNSIGNED,
    created_when DATE,
    FOREIGN KEY(created_by) REFERENCES accounts(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS people_vacancies(
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    p_id INT UNSIGNED,
    v_id INT UNSIGNED,
    FOREIGN KEY(p_id) REFERENCES people(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(v_id) REFERENCES vacancies(id) ON DELETE CASCADE ON UPDATE CASCADE
);
